#ifndef _MODULES_H_
#define _MODULES_H_

#include "stdint.h"

namespace sirius {

enum ModuleType {
    MODULE_OTHERS,
    MODULE_SIRIUS,
    MODULE_SIRIUS_IMPL,
    MODULE_SIRIUS_CORE,
    MODULE_SOCKET,
    MODULE_SOCKET_SERVER,
    MODULE_SOCKET_SERVER_SM,
    MODULE_SOCKET_CLIENT,
    MODULE_SOCKET_CLIENT_SM,
    MODULE_SERVER_CLIENT_CONTROL,
    MODULE_BUF_MANAGER,
    MODULE_ION_BUF_MANAGER,
    MODULE_SERVER_CB_THREAD,
    MODULE_RUN_ONCE_THREAD,
    MODULE_THREAD_POOL,
    MODULE_MEMORY_POOL,
    MODULE_REQUEST_HANDLER,
    MODULE_REQUEST_CLIENT_HANDLER,
    MODULE_SIRIUS_CLIENT_CORE,
    MODULE_PREVIEW_REQUEST,
    MODULE_YUV_PICTURE_REQUEST,
    MODULE_BAYER_PICTURE_REQUEST,
    MODULE_EVT_REQUEST,
    MODULE_DATA_REQUEST,
    MODULE_OBJECT_BUFFER,
    MODULE_UTILS,
    MODULE_TOOLS,
    MODULE_SERVER_TESTER,
    MODULE_CLIENT_TESTER,
    MODULE_TESTER,
    MODULE_MAX_INVALID,
};

const char *getModuleName(ModuleType type);
const char *getModuleShortName(ModuleType type);
uint32_t getMaxLenofShortName();

};

#endif

